// ...existing code...
app.get('/register', (req, res) => {
    const messages = req.flash('error'); // or however you are setting messages
    res.render('register', { messages });
});
// ...existing code...
app.post('/auth/register', (req, res) => {
    // ...existing code...
    if (error) {
        req.flash('error', 'Registration failed');
        return res.redirect('/register');
    }
    // ...existing code...
});
// ...existing code...
